name: flutter_aria2
description: Use "JSON-RPC 2.0" to connect Aria2.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.0.9
  json_rpc_2: ^2.0.9

dev_dependencies:
  build_runner: ^1.1.2